#localized string data for verbose messaging, errors, and warnings.

ConvertFrom-StringData @"
    SynchHash = Building a synchronized hashtable
    CantFind = Can not find a running PSClock in this PowerShell session. Do you need to start one?
    CreatingFlag = Creating the flag file: {0}
    DefiningRunspace = Defining the runspace command
    DefiningWPF = Defining the WPF form and controls
    Detected = Detected PowerShell host: {0}
    DotSource = Dot-sourcing module functions
    ExistingConsoleClock = An existing console clock has been detected
    ExistingTitleClock = An existing session title clock has been detected
    Ending = Ending module command: {0}
    FlagFound = A running clock has been detected from another PowerShell session on this desktop: \n\n{0}\n\nIf this is incorrect, delete {1} and try again.
    Importing = Importing module version {0}
    Launching = Launching the runspace
    LoadingColor = Loading color values
    LoadingFont = Loading font families
    Measuring = Measuring primary display
    NoConsoleClock = No running console clock found in this session
    NoTitleClock = No running session title clock found
    RegisterColorCompleter = Registering argument completer for Color
    RegisterConsoleClock = Creating event hidden event registration for a console clock
    ResisterTitleClock = Creating event hidden event registration for a session title clock
    RegisterFontCompleter = Registering argument completer for FontFamily
    RemovePrompt = Do you want to remove the flag file? Y/N
    Running = Running in PowerShell: {0}
    Saving = Saving PSClock settings to: {0}
    Setting = Setting {0} to {1}
    Showing = Showing the WPF form
    Starting = Starting module command: {0}
    StoppingConsole = Stopping console clock
    StoppingTitle = Stopping session title clock
    WarnDateFormat = The DateFormat value {0} is not a valid format string. Try something like F, G, or U, which are case-sensitive.
    Register = Registering hidden onIdle event subscription
    Requires = This requires Windows PowerShell or PowerShell 7 on Windows
    RequiresConsole = This command requires the console host
    Restoring = Restoring saved window session title
    Unregister = Unregistering event id: {0}
    UsingDateFormat = Using date time settings: {0}
    UsingText = Using sample text: {0}
    UsingFlag = Using flag file path {0}
    UsingImported = Using imported value for: {0}
    UsingModule = Using PSClock module version {0}
    UsingPath = Using save path: {0}
    UsingSaved = Using saved settings
    UsingSubscription = Using subscription id: {0}
    Validating = Validating clock parameter values
    WindowsOnly = This module requires a Windows platform.
    RunningClock = You already have a clock running. You can only have one clock running at a time.
"@
